const recipes = [
    {
        id: 'spaghetti-carbonara',
        name: 'Spaghetti Carbonara',
        cuisine: 'italian',
        description: 'A traditional Roman pasta dish featuring a creamy sauce made from eggs, cheese, and crispy pancetta, without using cream.',
        cookingTime: 20,
        serves: 4,
        ingredients: ['400g spaghetti', '200g pancetta or guanciale, diced', '4 large eggs', '100g Pecorino Romano cheese, grated', '50g Parmesan cheese, grated', 'Black pepper, freshly ground', 'Salt for pasta water'],
        instructions: [
            'Bring a large pot of salted water to boil for the pasta',
            'In a large bowl, whisk together eggs, Pecorino Romano, Parmesan, and plenty of black pepper',
            'Heat a large skillet over medium heat and cook pancetta until crispy (5-7 minutes)',
            'Cook spaghetti according to package directions until al dente',
            'Reserve 1 cup of pasta cooking water before draining',
            'Add hot pasta to the skillet with pancetta',
            'Remove from heat and quickly toss with egg mixture, adding pasta water gradually to create a creamy sauce',
            'Serve immediately with extra cheese and black pepper'
        ]
    },
    {
        id: 'margherita-pizza',
        name: 'Margherita Pizza',
        cuisine: 'italian',
        description: 'The quintessential Neapolitan pizza representing the colors of the Italian flag with simple, high-quality ingredients.',
        cookingTime: 120,
        serves: 4,
        ingredients: ['500g bread flour', '325ml warm water', '7g active dry yeast', '10ml olive oil', '10g salt', '400g canned San Marzano tomatoes, crushed', '250g fresh mozzarella, sliced', 'Fresh basil leaves', 'Extra virgin olive oil'],
        instructions: [
            'Dissolve yeast in warm water and let stand for 5 minutes until foamy',
            'Mix flour and salt in a large bowl, add yeast mixture and olive oil',
            'Knead dough for 10 minutes until smooth and elastic',
            'Place in oiled bowl, cover, and rise for 1 hour',
            'Preheat oven to 475°F (245°C) with pizza stone if available',
            'Divide dough in half and stretch into 12-inch circles',
            'Spread crushed tomatoes evenly, leaving 1-inch border',
            'Add mozzarella slices and drizzle with olive oil',
            'Bake for 10-12 minutes until crust is golden and cheese bubbles',
            'Top with fresh basil leaves and serve immediately'
        ]
    },
    {
        id: 'chicken-fried-rice',
        name: 'Chicken Fried Rice',
        cuisine: 'asian',
        description: 'A popular Chinese-American dish combining day-old rice with chicken, vegetables, and soy sauce for a satisfying one-pan meal.',
        cookingTime: 15,
        serves: 4,
        ingredients: ['4 cups cooked rice, preferably day-old', '2 chicken breasts, diced', '3 eggs, beaten', '2 carrots, diced', '1 cup frozen peas', '3 green onions, chopped', '3 cloves garlic, minced', '3 tbsp soy sauce', '2 tbsp vegetable oil', '1 tbsp sesame oil', 'Salt and pepper to taste'],
        instructions: [
            'Heat 1 tablespoon oil in large wok or skillet over high heat',
            'Add beaten eggs and scramble, then remove and set aside',
            'Add remaining oil and cook diced chicken until golden (5-6 minutes)',
            'Add garlic, carrots, and peas, stir-fry for 2 minutes',
            'Add cold rice, breaking up clumps with spatula',
            'Stir in soy sauce and sesame oil, mixing thoroughly',
            'Return scrambled eggs to pan and add green onions',
            'Stir-fry for 2 more minutes until heated through',
            'Season with salt and pepper, serve hot'
        ]
    },
    {
        id: 'beef-teriyaki',
        name: 'Beef Teriyaki',
        cuisine: 'asian',
        description: 'Japanese-inspired dish featuring tender beef in a sweet and savory teriyaki glaze, perfect over rice.',
        cookingTime: 25,
        serves: 4,
        ingredients: ['600g beef sirloin, sliced thin', '1/3 cup soy sauce', '1/4 cup mirin', '2 tbsp brown sugar', '1 tbsp rice vinegar', '2 cloves garlic, minced', '1 tsp fresh ginger, grated', '2 tbsp vegetable oil', '1 tbsp cornstarch', '2 tbsp water', 'Sesame seeds for garnish'],
        instructions: [
            'Combine soy sauce, mirin, brown sugar, vinegar, garlic, and ginger for sauce',
            'Heat oil in large skillet over medium-high heat',
            'Cook beef strips in batches until browned (2-3 minutes per side)',
            'Remove beef and set aside',
            'Pour sauce into same skillet and bring to simmer',
            'Mix cornstarch with water and add to sauce to thicken',
            'Return beef to skillet and toss to coat with glaze',
            'Cook for 2 more minutes until sauce coats beef',
            'Garnish with sesame seeds and serve over rice'
        ]
    },
    {
        id: 'chicken-tacos',
        name: 'Chicken Tacos',
        cuisine: 'mexican',
        description: 'Traditional Mexican street-style tacos with perfectly seasoned chicken and fresh accompaniments.',
        cookingTime: 30,
        serves: 6,
        ingredients: ['800g chicken thighs, boneless and skinless', '2 tsp chili powder', '1 tsp cumin', '1 tsp paprika', '1/2 tsp oregano', '1/2 tsp garlic powder', 'Salt and pepper', '12 corn tortillas', '1 white onion, diced', 'Fresh cilantro, chopped', '2 limes, cut into wedges', 'Salsa verde', 'Mexican crema or sour cream'],
        instructions: [
            'Season chicken with all spices, salt, and pepper',
            'Heat grill or skillet over medium-high heat',
            'Cook chicken for 6-7 minutes per side until internal temperature reaches 165°F',
            'Let chicken rest for 5 minutes, then slice or chop',
            'Warm tortillas on dry skillet for 30 seconds per side',
            'Fill tortillas with chicken',
            'Top with diced onion, cilantro, and salsa verde',
            'Serve with lime wedges and crema',
            'Fold and enjoy immediately'
        ]
    },
    {
        id: 'guacamole',
        name: 'Guacamole',
        cuisine: 'mexican',
        description: 'Classic Mexican avocado dip that\'s fresh, flavorful, and perfect for any gathering.',
        cookingTime: 10,
        serves: 6,
        ingredients: ['4 ripe avocados', '1 small white onion, finely diced', '2 Roma tomatoes, seeded and diced', '2 jalapeño peppers, seeded and minced', '3 cloves garlic, minced', '3 limes, juiced', '1/2 cup fresh cilantro, chopped', 'Salt to taste'],
        instructions: [
            'Cut avocados in half, remove pits, and scoop into large bowl',
            'Mash avocados with fork, leaving some chunks for texture',
            'Add lime juice immediately to prevent browning',
            'Mix in diced onion, tomatoes, and jalapeños',
            'Add minced garlic and chopped cilantro',
            'Season with salt to taste',
            'Mix gently to combine all ingredients',
            'Taste and adjust lime juice and salt as needed',
            'Serve immediately with tortilla chips'
        ]
    },
    {
        id: 'coq-au-vin',
        name: 'Coq au Vin',
        cuisine: 'french',
        description: 'A classic French braised chicken dish cooked in red wine with mushrooms, onions, and herbs.',
        cookingTime: 90,
        serves: 6,
        ingredients: ['1 whole chicken, cut into pieces', '4 slices bacon, chopped', '12 pearl onions, peeled', '250g mushrooms, quartered', '3 cloves garlic, minced', '2 tbsp tomato paste', '3 cups red wine (Burgundy preferred)', '2 cups chicken broth', '2 bay leaves', '3 sprigs fresh thyme', '2 tbsp butter', '2 tbsp flour', 'Salt and pepper'],
        instructions: [
            'Season chicken pieces with salt and pepper',
            'Cook bacon in Dutch oven until crispy, remove and set aside',
            'Brown chicken pieces in bacon fat, about 4 minutes per side',
            'Remove chicken and sauté onions and mushrooms until golden',
            'Add garlic and tomato paste, cook for 1 minute',
            'Add wine, scraping up browned bits from bottom',
            'Return chicken and bacon to pot',
            'Add broth, bay leaves, and thyme, bring to simmer',
            'Cover and cook for 45 minutes until chicken is tender',
            'Mix butter and flour to make paste, stir into sauce to thicken',
            'Simmer 5 more minutes and serve hot'
        ]
    },
    {
        id: 'french-onion-soup',
        name: 'French Onion Soup',
        cuisine: 'french',
        description: 'A deeply flavorful soup featuring caramelized onions in beef broth, topped with crusty bread and melted cheese.',
        cookingTime: 75,
        serves: 6,
        ingredients: ['6 large yellow onions, thinly sliced', '4 tbsp butter', '2 tbsp olive oil', '1 tsp sugar', '1/2 cup dry white wine', '6 cups beef broth', '2 bay leaves', '6 slices French bread', '200g Gruyère cheese, grated', 'Salt and pepper'],
        instructions: [
            'Heat butter and oil in large pot over medium heat',
            'Add onions and sugar, cook slowly for 45 minutes, stirring occasionally',
            'Onions should become deep golden brown and caramelized',
            'Add wine and scrape up any browned bits',
            'Add broth and bay leaves, bring to boil',
            'Reduce heat and simmer for 20 minutes',
            'Season with salt and pepper',
            'Preheat broiler and toast bread slices',
            'Ladle soup into oven-safe bowls',
            'Top each with bread slice and generous amount of cheese',
            'Broil until cheese is bubbly and golden',
            'Serve immediately while hot'
        ]
    },
    {
        id: 'chicken-curry',
        name: 'Chicken Curry',
        cuisine: 'indian',
        description: 'A fragrant and mildly spiced chicken curry in a tomato-based sauce with traditional Indian spices.',
        cookingTime: 45,
        serves: 6,
        ingredients: ['800g chicken, cut into pieces', '2 large onions, chopped', '4 cloves garlic, minced', '2 tbsp fresh ginger, grated', '2 tbsp vegetable oil', '2 tsp ground cumin', '2 tsp ground coriander', '1 tsp turmeric', '1 tsp garam masala', '1/2 tsp cayenne pepper', '400g canned tomatoes, crushed', '400ml coconut milk', 'Salt to taste', 'Fresh cilantro for garnish'],
        instructions: [
            'Heat oil in large pot over medium heat',
            'Sauté onions until golden brown, about 8 minutes',
            'Add garlic and ginger, cook for 1 minute',
            'Add all spices and cook until fragrant, 30 seconds',
            'Add crushed tomatoes and cook for 5 minutes',
            'Add chicken pieces and cook until no longer pink',
            'Pour in coconut milk and bring to simmer',
            'Cover and cook for 20 minutes until chicken is tender',
            'Season with salt to taste',
            'Garnish with fresh cilantro and serve with rice'
        ]
    },
    {
        id: 'naan-bread',
        name: 'Naan Bread',
        cuisine: 'indian',
        description: 'Traditional Indian flatbread that\'s soft, chewy, and perfect for scooping up curries.',
        cookingTime: 120,
        serves: 8,
        ingredients: ['500g bread flour', '250ml warm water', '125ml plain yogurt', '2 tsp active dry yeast', '2 tsp sugar', '1 tsp salt', '3 tbsp vegetable oil', '4 tbsp butter, melted', '2 cloves garlic, minced (optional)'],
        instructions: [
            'Dissolve yeast and sugar in warm water, let stand 5 minutes',
            'Mix flour and salt in large bowl',
            'Add yeast mixture, yogurt, and oil to flour',
            'Knead for 8 minutes until smooth and elastic',
            'Place in oiled bowl, cover, and rise for 1 hour',
            'Divide dough into 8 portions and roll into ovals',
            'Heat cast iron skillet or grill pan over high heat',
            'Cook naan for 1-2 minutes until puffed and spotted',
            'Flip and cook 1 more minute',
            'Brush with melted butter and garlic if desired',
            'Serve warm'
        ]
    },
    {
        id: 'classic-hamburger',
        name: 'Classic Hamburger',
        cuisine: 'american',
        description: 'The quintessential American sandwich featuring a seasoned beef patty with classic toppings.',
        cookingTime: 20,
        serves: 4,
        ingredients: ['600g ground beef (80/20 blend)', '4 hamburger buns', '4 slices cheese (American or cheddar)', '1 large tomato, sliced', 'Lettuce leaves', '1 onion, sliced', 'Pickles', 'Ketchup, mustard, mayo', 'Salt and pepper'],
        instructions: [
            'Form ground beef into 4 patties, slightly larger than buns',
            'Season both sides with salt and pepper',
            'Heat grill or skillet over medium-high heat',
            'Cook patties for 4 minutes without pressing down',
            'Flip and cook 3-4 more minutes for medium',
            'Add cheese in last minute of cooking',
            'Toast buns lightly on grill or in toaster',
            'Assemble burgers with desired toppings',
            'Serve immediately with fries or chips'
        ]
    },
    {
        id: 'apple-pie',
        name: 'Apple Pie',
        cuisine: 'american',
        description: 'The classic American dessert featuring spiced apples in a flaky, buttery crust.',
        cookingTime: 90,
        serves: 8,
        ingredients: ['2 pie crusts (homemade or store-bought)', '8 large apples, peeled and sliced', '3/4 cup granulated sugar', '2 tbsp brown sugar', '2 tbsp flour', '1 tsp cinnamon', '1/4 tsp nutmeg', '1/4 tsp salt', '2 tbsp butter, cubed', '1 egg, beaten for wash'],
        instructions: [
            'Preheat oven to 425°F (220°C)',
            'Roll out bottom crust and place in 9-inch pie pan',
            'Mix apples with both sugars, flour, spices, and salt',
            'Fill crust with apple mixture and dot with butter',
            'Cover with top crust or create lattice pattern',
            'Trim and crimp edges to seal',
            'Brush top with beaten egg',
            'Cut several slits for steam vents',
            'Bake for 45-50 minutes until crust is golden',
            'Cool for at least 30 minutes before serving'
        ]
    },
    {
        id: 'greek-moussaka',
        name: 'Greek Moussaka',
        cuisine: 'mediterranean',
        description: 'A traditional Greek baked dish with layers of eggplant, spiced meat sauce, and creamy béchamel topping.',
        cookingTime: 120,
        serves: 8,
        ingredients: ['3 large eggplants, sliced', '500g ground lamb or beef', '1 large onion, chopped', '3 cloves garlic, minced', '400g canned tomatoes', '2 tbsp tomato paste', '1/2 cup red wine', '1 tsp oregano', '1/2 tsp cinnamon', '4 tbsp olive oil', '50g butter', '50g flour', '500ml milk', '100g Parmesan cheese, grated', '2 egg yolks', 'Salt and pepper'],
        instructions: [
            'Salt eggplant slices and let drain for 30 minutes',
            'Rinse and pat dry, then brush with olive oil',
            'Grill or bake eggplant until golden, about 6 minutes per side',
            'Brown meat with onion and garlic in large skillet',
            'Add tomatoes, tomato paste, wine, oregano, and cinnamon',
            'Simmer for 20 minutes until sauce thickens',
            'For béchamel: melt butter, whisk in flour, gradually add milk',
            'Cook until thick, then stir in cheese and egg yolks',
            'Layer eggplant, meat sauce, and more eggplant in baking dish',
            'Top with béchamel sauce',
            'Bake at 350°F (175°C) for 45 minutes until golden',
            'Cool for 15 minutes before serving'
        ]
    },
    {
        id: 'hummus',
        name: 'Hummus',
        cuisine: 'mediterranean',
        description: 'A Middle Eastern dip made from chickpeas, tahini, and lemon juice, perfect with pita bread.',
        cookingTime: 10,
        serves: 6,
        ingredients: ['400g canned chickpeas, drained', '1/4 cup fresh lemon juice', '1/4 cup tahini', '1 clove garlic, minced', '2 tbsp extra virgin olive oil', '1/2 tsp ground cumin', 'Salt to taste', '2-3 tbsp water', 'Paprika for garnish'],
        instructions: [
            'Combine tahini and lemon juice in food processor',
            'Process for 1 minute until creamy',
            'Add olive oil, garlic, cumin, and salt',
            'Process for 30 seconds',
            'Add half the chickpeas and process 1 minute',
            'Add remaining chickpeas and process until smooth',
            'Add water as needed for desired consistency',
            'Taste and adjust seasonings',
            'Transfer to serving bowl',
            'Drizzle with olive oil and sprinkle with paprika',
            'Serve with pita bread or vegetables'
        ]
    },
    {
        id: 'chocolate-chip-cookies',
        name: 'Chocolate Chip Cookies',
        cuisine: 'desserts',
        description: 'The classic American cookie that\'s crispy on the edges and chewy in the center.',
        cookingTime: 25,
        serves: 24,
        ingredients: ['225g butter, softened', '150g brown sugar, packed', '100g granulated sugar', '2 large eggs', '2 tsp vanilla extract', '350g all-purpose flour', '1 tsp baking soda', '1 tsp salt', '300g chocolate chips'],
        instructions: [
            'Preheat oven to 375°F (190°C)',
            'Cream butter with both sugars until light and fluffy',
            'Beat in eggs one at a time, then vanilla',
            'Mix flour, baking soda, and salt in separate bowl',
            'Gradually blend flour mixture into butter mixture',
            'Stir in chocolate chips',
            'Drop rounded tablespoons onto ungreased baking sheets',
            'Bake for 9-11 minutes until golden brown',
            'Cool on baking sheet for 2 minutes',
            'Transfer to wire rack to cool completely'
        ]
    },
    {
        id: 'tiramisu',
        name: 'Tiramisu',
        cuisine: 'desserts',
        description: 'An elegant Italian dessert with layers of coffee-soaked ladyfingers and mascarpone cream.',
        cookingTime: 270,
        serves: 8,
        ingredients: ['6 egg yolks', '150g granulated sugar', '500g mascarpone cheese', '2 cups strong espresso, cooled', '3 tbsp coffee liqueur (optional)', '2 packages ladyfinger cookies', 'Unsweetened cocoa powder', 'Dark chocolate for shaving'],
        instructions: [
            'Whisk egg yolks and sugar until thick and pale',
            'Add mascarpone and beat until smooth',
            'Combine coffee and liqueur in shallow dish',
            'Quickly dip each ladyfinger in coffee mixture',
            'Arrange in single layer in 9x13 inch dish',
            'Spread half the mascarpone mixture over cookies',
            'Repeat with another layer of dipped cookies',
            'Top with remaining mascarpone mixture',
            'Cover and refrigerate for at least 4 hours',
            'Before serving, dust with cocoa powder',
            'Garnish with chocolate shavings if desired'
        ]
    },
    {
        id: 'creme-brulee',
        name: 'Crème Brûlée',
        cuisine: 'desserts',
        description: 'A rich French custard dessert topped with a layer of hardened caramelized sugar.',
        cookingTime: 180,
        serves: 6,
        ingredients: ['2 cups heavy cream', '1 vanilla bean or 2 tsp vanilla extract', '5 egg yolks', '1/3 cup granulated sugar (plus extra for topping)', 'Pinch of salt'],
        instructions: [
            'Preheat oven to 325°F (165°C)',
            'Heat cream with vanilla bean in saucepan until just simmering',
            'Remove vanilla bean and scrape seeds back into cream',
            'Whisk egg yolks with sugar and salt until smooth',
            'Gradually whisk hot cream into egg mixture',
            'Strain mixture through fine-mesh sieve',
            'Divide among 6 ramekins',
            'Place ramekins in baking dish and add hot water halfway up sides',
            'Bake for 35-40 minutes until just set but still jiggly',
            'Cool completely, then refrigerate for at least 2 hours',
            'Before serving, sprinkle with sugar and caramelize with torch',
            'Let sugar harden for 2 minutes before serving'
        ]
    },
    {
        id: 'butter-chicken',
        name: 'Butter Chicken',
        cuisine: 'indian',
        description: 'Creamy tomato-based curry with tender chicken pieces in a rich, mildly spiced sauce.',
        cookingTime: 60,
        serves: 4,
        ingredients: ['800g chicken breast, cubed', '200g plain yogurt', '2 tsp garam masala', '1 tsp cumin powder', '1 tsp coriander powder', '1/2 tsp turmeric', '3 tbsp butter', '1 large onion, chopped', '4 cloves garlic, minced', '2 tbsp ginger paste', '400g canned tomatoes', '200ml heavy cream', '1 tbsp tomato paste', '1 tsp red chili powder', 'Salt to taste', 'Fresh cilantro'],
        instructions: [
            'Marinate chicken with yogurt, 1 tsp garam masala, salt for 30 minutes',
            'Heat butter in pan, cook marinated chicken until done, set aside',
            'In same pan, sauté onions until golden',
            'Add garlic, ginger, cook for 1 minute',
            'Add tomato paste, remaining spices, cook 2 minutes',
            'Add canned tomatoes, simmer 10 minutes',
            'Blend sauce until smooth, return to pan',
            'Add cream, cooked chicken, simmer 10 minutes',
            'Garnish with cilantro, serve with rice or naan'
        ]
    },
    {
        id: 'biryani',
        name: 'Chicken Biryani',
        cuisine: 'indian',
        description: 'Aromatic layered rice dish with spiced chicken, saffron, and fried onions.',
        cookingTime: 90,
        serves: 6,
        ingredients: ['500g basmati rice', '800g chicken, cut in pieces', '4 large onions, sliced', '1 cup yogurt', '2 tbsp ginger-garlic paste', '2 tsp red chili powder', '1 tsp turmeric', '2 tsp garam masala', '1/2 cup mint leaves', '1/2 cup cilantro', '1/4 cup ghee', 'Saffron strands', '1/2 cup warm milk', '4 green cardamom', '2 black cardamom', '4 cloves', '2 bay leaves', '1 cinnamon stick', 'Salt to taste'],
        instructions: [
            'Soak basmati rice for 30 minutes, drain',
            'Deep fry sliced onions until golden, drain on paper',
            'Marinate chicken with yogurt, ginger-garlic paste, spices, salt for 1 hour',
            'Cook marinated chicken until 80% done, set aside',
            'Boil water with whole spices, add rice, cook until 70% done',
            'Soak saffron in warm milk',
            'Layer rice and chicken in heavy-bottomed pot',
            'Sprinkle fried onions, mint, cilantro, saffron milk, ghee',
            'Cover with foil, then lid, cook on high heat 3 minutes',
            'Reduce heat to lowest, cook 45 minutes',
            'Let rest 10 minutes before opening',
            'Serve hot with raita and pickles'
        ]
    },
    {
        id: 'dal-tadka',
        name: 'Dal Tadka',
        cuisine: 'indian',
        description: 'Yellow lentils cooked with spices and finished with aromatic tempering.',
        cookingTime: 40,
        serves: 4,
        ingredients: ['1 cup yellow dal (tuvar/arhar)', '3 cups water', '1/2 tsp turmeric', '1 tsp salt', '2 tbsp ghee', '1 tsp cumin seeds', '1 tsp mustard seeds', '2 dried red chilies', '4 cloves garlic, chopped', '1 inch ginger, chopped', '1 green chili, slit', '1 medium onion, chopped', '2 tomatoes, chopped', '1/2 tsp red chili powder', '1/2 tsp garam masala', 'Fresh cilantro', 'Lemon juice'],
        instructions: [
            'Wash dal, add water, turmeric, salt, pressure cook 3 whistles',
            'Mash cooked dal lightly, keep aside',
            'Heat ghee in pan, add cumin and mustard seeds',
            'When they splutter, add red chilies, garlic, ginger',
            'Add green chili and onions, sauté until golden',
            'Add tomatoes, cook until soft',
            'Add chili powder and garam masala, mix well',
            'Add cooked dal, simmer 10 minutes',
            'Adjust consistency with water if needed',
            'Garnish with cilantro and lemon juice',
            'Serve hot with rice or roti'
        ]
    },
    {
        id: 'palak-paneer',
        name: 'Palak Paneer',
        cuisine: 'indian',
        description: 'Creamy spinach curry with soft paneer cubes, rich in flavor and nutrition.',
        cookingTime: 45,
        serves: 4,
        ingredients: ['500g fresh spinach', '250g paneer, cubed', '2 large onions, chopped', '4 tomatoes, chopped', '6 cloves garlic', '2 inch ginger', '2 green chilies', '1 tsp cumin seeds', '1 tsp garam masala', '1/2 tsp turmeric', '1 tsp red chili powder', '3 tbsp oil', '2 tbsp cream', 'Salt to taste'],
        instructions: [
            'Blanch spinach in boiling water for 2 minutes, drain and cool',
            'Blend spinach with little water to smooth paste',
            'Heat oil, lightly fry paneer cubes until golden, set aside',
            'In same oil, add cumin seeds, let them splutter',
            'Add onions, sauté until golden brown',
            'Add ginger-garlic paste and green chilies, cook 2 minutes',
            'Add tomatoes, cook until soft and mushy',
            'Add turmeric, chili powder, garam masala, cook 2 minutes',
            'Add spinach puree, mix well, simmer 10 minutes',
            'Add paneer cubes and cream, simmer 5 minutes',
            'Season with salt, serve hot with roti or rice'
        ]
    },
    {
        id: 'chole-bhature',
        name: 'Chole Bhature',
        cuisine: 'indian',
        description: 'Spicy chickpea curry served with deep-fried fluffy bread.',
        cookingTime: 120,
        serves: 4,
        ingredients: ['2 cups dried chickpeas', '2 bay leaves', '4 green cardamom', '1 black cardamom', '1 cinnamon stick', '3 large onions, chopped', '4 tomatoes, chopped', '2 tbsp ginger-garlic paste', '2 tsp red chili powder', '1 tsp turmeric', '2 tsp coriander powder', '1 tsp garam masala', '1 tsp amchur powder', '3 tbsp oil', 'Salt to taste', 'For Bhature: 2 cups maida, 1/2 cup yogurt, 1/2 tsp baking soda, Salt, Oil for frying'],
        instructions: [
            'Soak chickpeas overnight, pressure cook with whole spices until soft',
            'For bhature: mix maida, yogurt, baking soda, salt, knead soft dough',
            'Rest dough for 2 hours',
            'Heat oil, sauté onions until golden',
            'Add ginger-garlic paste, cook 2 minutes',
            'Add tomatoes, cook until soft',
            'Add all spices, cook 5 minutes',
            'Add cooked chickpeas with cooking liquid',
            'Simmer 30 minutes until thick',
            'Roll bhature, deep fry until puffed and golden',
            'Serve hot chole with bhature, onions, pickles'
        ]
    },
    {
        id: 'rajma',
        name: 'Rajma',
        cuisine: 'indian',
        description: 'Kidney bean curry in thick, spiced tomato gravy, popular in North India.',
        cookingTime: 90,
        serves: 4,
        ingredients: ['2 cups rajma (kidney beans)', '3 large onions, chopped', '4 tomatoes, chopped', '2 tbsp ginger-garlic paste', '2 tsp red chili powder', '1 tsp turmeric', '2 tsp coriander powder', '1 tsp garam masala', '2 bay leaves', '3 tbsp oil', '1 tbsp butter', 'Salt to taste', 'Fresh cilantro'],
        instructions: [
            'Soak rajma overnight, pressure cook until very soft',
            'Heat oil and butter, add bay leaves',
            'Add onions, sauté until golden brown',
            'Add ginger-garlic paste, cook 2 minutes',
            'Add tomatoes, cook until completely soft',
            'Add all spices, cook 5 minutes',
            'Mash some cooked rajma, add to pan with cooking liquid',
            'Simmer 30 minutes until thick gravy forms',
            'Mash few more beans for thick consistency',
            'Garnish with cilantro',
            'Serve hot with rice'
        ]
    },
    {
        id: 'aloo-gobi',
        name: 'Aloo Gobi',
        cuisine: 'indian',
        description: 'Dry curry of potatoes and cauliflower with aromatic spices.',
        cookingTime: 30,
        serves: 4,
        ingredients: ['500g cauliflower, cut in florets', '4 medium potatoes, cubed', '2 large onions, sliced', '2 tomatoes, chopped', '2 tsp ginger-garlic paste', '2 tsp cumin seeds', '1 tsp turmeric', '2 tsp coriander powder', '1 tsp red chili powder', '1 tsp garam masala', '3 tbsp oil', 'Salt to taste', 'Fresh cilantro'],
        instructions: [
            'Heat oil in heavy-bottomed pan',
            'Add cumin seeds, let them splutter',
            'Add onions, sauté until golden',
            'Add ginger-garlic paste, cook 1 minute',
            'Add tomatoes, coriander powder, turmeric, chili powder',
            'Cook until tomatoes are soft',
            'Add potatoes, mix well, cover and cook 10 minutes',
            'Add cauliflower, salt, mix gently',
            'Cover and cook 15 minutes, stirring occasionally',
            'Sprinkle garam masala and cilantro',
            'Serve hot with roti or rice'
        ]
    },
    {
        id: 'samosa',
        name: 'Samosa',
        cuisine: 'indian',
        description: 'Crispy triangular pastries filled with spiced potato and pea mixture.',
        cookingTime: 60,
        serves: 20,
        ingredients: ['For dough: 2 cups maida, 4 tbsp oil, 1/2 tsp salt, Water as needed', 'For filling: 4 large potatoes, boiled and cubed', '1 cup green peas', '2 tsp cumin seeds', '1 tsp fennel seeds', '2 green chilies, chopped', '1 inch ginger, chopped', '1 tsp red chili powder', '1 tsp garam masala', '1 tsp amchur powder', '2 tbsp oil', 'Salt to taste', 'Oil for deep frying'],
        instructions: [
            'Mix maida, oil, salt, add water gradually to make stiff dough',
            'Rest dough for 30 minutes',
            'For filling: heat oil, add cumin and fennel seeds',
            'Add ginger, green chilies, sauté briefly',
            'Add peas, cook 3 minutes',
            'Add potatoes, all spices, salt, mix well',
            'Cool the filling completely',
            'Roll dough into small circles, cut in half',
            'Form cone with each half, fill with mixture',
            'Seal edges with water',
            'Deep fry in hot oil until golden and crispy',
            'Serve hot with mint chutney'
        ]
    },
    {
        id: 'dosa',
        name: 'Masala Dosa',
        cuisine: 'indian',
        description: 'Crispy South Indian crepe made from fermented rice and lentil batter, filled with spiced potatoes.',
        cookingTime: 240,
        serves: 6,
        ingredients: ['3 cups parboiled rice', '1 cup urad dal', '1/2 cup poha (flattened rice)', '1 tsp fenugreek seeds', 'Salt to taste', 'Oil for cooking', 'For filling: 6 potatoes, boiled', '2 large onions, sliced', '2 tsp mustard seeds', '1 tsp cumin seeds', '10 curry leaves', '2 green chilies', '1/2 tsp turmeric', '2 tbsp oil', 'Salt to taste'],
        instructions: [
            'Soak rice, urad dal, fenugreek seeds separately for 4 hours',
            'Soak poha for 30 minutes',
            'Grind urad dal with poha to smooth paste',
            'Grind rice to slightly coarse paste',
            'Mix both batters, add salt, ferment 8-12 hours',
            'For filling: heat oil, add mustard seeds, cumin seeds',
            'Add curry leaves, onions, green chilies',
            'Add turmeric, mashed potatoes, salt, mix well',
            'Heat non-stick pan, pour batter, spread thin',
            'Drizzle oil around edges, cook until golden',
            'Place potato filling on one side, fold dosa',
            'Serve hot with sambar and coconut chutney'
        ]
    },
    {
        id: 'idli-sambar',
        name: 'Idli Sambar',
        cuisine: 'indian',
        description: 'Steamed rice cakes served with spiced lentil soup, a South Indian staple.',
        cookingTime: 180,
        serves: 4,
        ingredients: ['For Idli: 3 cups parboiled rice', '1 cup urad dal', 'Salt to taste', 'For Sambar: 1 cup toor dal', '2 tbsp sambar powder', '1 tsp turmeric', '2 tomatoes, chopped', '1 onion, chopped', '1 brinjal, cubed', '1 drumstick, cut in pieces', '10 okra, chopped', '1 tbsp tamarind paste', '2 tbsp oil', '1 tsp mustard seeds', '1 tsp cumin seeds', '2 dried red chilies', '10 curry leaves', 'Salt to taste'],
        instructions: [
            'Soak rice and urad dal separately for 4 hours',
            'Grind urad dal to fluffy paste, rice to smooth paste',
            'Mix both batters, add salt, ferment overnight',
            'Steam idli batter in idli plates for 12-15 minutes',
            'For sambar: pressure cook toor dal until soft',
            'Heat oil, add mustard seeds, cumin seeds, red chilies',
            'Add curry leaves, onions, sauté until soft',
            'Add vegetables, turmeric, cook 5 minutes',
            'Add tomatoes, sambar powder, cook until soft',
            'Add cooked dal, tamarind paste, salt',
            'Simmer 15 minutes until vegetables are tender',
            'Serve hot idlis with sambar and coconut chutney'
        ]
    },
    {
        id: 'vada-pav',
        name: 'Vada Pav',
        cuisine: 'indian',
        description: 'Mumbai street food consisting of spiced potato fritter in a bun with chutneys.',
        cookingTime: 45,
        serves: 4,
        ingredients: ['4 pav (burger buns)', 'For vada: 4 large potatoes, boiled', '2 green chilies, chopped', '1 inch ginger, chopped', '1/2 tsp turmeric', '1 tsp mustard seeds', '10 curry leaves', '2 tbsp oil', 'Salt to taste', 'For batter: 1 cup besan', '1/2 tsp turmeric', '1/2 tsp red chili powder', 'Water as needed', 'Oil for frying', 'Green chutney and dry garlic chutney'],
        instructions: [
            'Mash boiled potatoes coarsely',
            'Heat oil, add mustard seeds, curry leaves',
            'Add ginger, green chilies, sauté briefly',
            'Add turmeric, mashed potatoes, salt, mix well',
            'Cool the mixture, make small balls',
            'Mix besan with spices and water to make thick batter',
            'Dip potato balls in batter, deep fry until golden',
            'Slit pav horizontally, apply chutneys',
            'Place hot vada inside pav',
            'Serve immediately with fried green chilies'
        ]
    },
    {
        id: 'pani-puri',
        name: 'Pani Puri',
        cuisine: 'indian',
        description: 'Popular street snack with crispy puris filled with spiced water, tamarind chutney, and chickpeas.',
        cookingTime: 30,
        serves: 4,
        ingredients: ['30 ready-made puris', '1 cup boiled chickpeas', '2 medium potatoes, boiled and cubed', 'For pani: 1 cup mint leaves', '1/2 cup cilantro', '2 green chilies', '1 inch ginger', '1 tsp roasted cumin powder', '1 tsp chaat masala', '1 tsp black salt', 'Salt to taste', '4 cups cold water', 'For sweet chutney: 1 cup tamarind pulp', '1 cup jaggery', '1 tsp red chili powder', '1 tsp roasted cumin powder'],
        instructions: [
            'For pani: blend mint, cilantro, green chilies, ginger with little water',
            'Mix this paste with cold water, add all spices',
            'Strain and chill the pani',
            'For chutney: cook tamarind pulp with jaggery until thick',
            'Add spices to chutney, cool completely',
            'Make small holes in puris carefully',
            'Fill each puri with chickpeas and potato pieces',
            'Add little sweet chutney',
            'Dip in spiced pani and eat immediately',
            'Serve with extra pani on the side'
        ]
    },
    {
        id: 'bhel-puri',
        name: 'Bhel Puri',
        cuisine: 'indian',
        description: 'Mumbai street food mix of puffed rice, sev, vegetables, and tangy chutneys.',
        cookingTime: 15,
        serves: 4,
        ingredients: ['4 cups puffed rice (murmura)', '1 cup sev (fine gram flour noodles)', '2 medium onions, finely chopped', '2 tomatoes, finely chopped', '2 boiled potatoes, cubed', '1/2 cup roasted peanuts', '1/4 cup chopped cilantro', 'Green chutney (mint-cilantro)', 'Sweet tamarind chutney', '1 tsp chaat masala', 'Lemon juice', 'Salt to taste'],
        instructions: [
            'Take puffed rice in large mixing bowl',
            'Add chopped onions, tomatoes, potatoes',
            'Add roasted peanuts and cilantro',
            'Add 2-3 tbsp green chutney and sweet chutney',
            'Sprinkle chaat masala and salt',
            'Add lemon juice to taste',
            'Mix everything gently but thoroughly',
            'Garnish with sev on top',
            'Serve immediately in paper cones or bowls'
        ]
    },
    {
        id: 'tandoori-chicken',
        name: 'Tandoori Chicken',
        cuisine: 'indian',
        description: 'Chicken marinated in yogurt and spices, traditionally cooked in a tandoor oven.',
        cookingTime: 120,
        serves: 4,
        ingredients: ['1 whole chicken, cut in pieces', '1 cup thick yogurt', '2 tbsp ginger-garlic paste', '2 tsp red chili powder', '1 tsp turmeric', '2 tsp garam masala', '1 tsp coriander powder', '1 tsp cumin powder', '1/2 tsp tandoori masala', '2 tbsp lemon juice', '3 tbsp mustard oil', '1 tsp salt', 'Red food coloring (optional)', 'Onion rings and lemon wedges for serving'],
        instructions: [
            'Make deep cuts in chicken pieces',
            'Mix yogurt with all spices, ginger-garlic paste, lemon juice',
            'Add mustard oil and food coloring if using',
            'Marinate chicken in this mixture for at least 2 hours',
            'Preheat oven to 220°C or prepare tandoor',
            'Thread chicken pieces on skewers',
            'Cook for 15-20 minutes, basting with oil',
            'Turn and cook another 10-15 minutes until charred edges',
            'Let rest for 5 minutes',
            'Serve hot with onion rings, lemon wedges, mint chutney'
        ]
    },
    {
        id: 'fish-curry',
        name: 'Fish Curry',
        cuisine: 'indian',
        description: 'South Indian style fish curry in coconut milk with curry leaves and spices.',
        cookingTime: 30,
        serves: 4,
        ingredients: ['500g fish fillets (kingfish or pomfret)', '400ml coconut milk', '2 large onions, sliced', '3 tomatoes, chopped', '2 tbsp ginger-garlic paste', '2 green chilies, slit', '15 curry leaves', '1 tsp turmeric', '2 tsp red chili powder', '2 tsp coriander powder', '1 tsp garam masala', '2 tbsp coconut oil', '1 tbsp tamarind paste', 'Salt to taste'],
        instructions: [
            'Cut fish into medium pieces, marinate with turmeric and salt',
            'Heat coconut oil in heavy-bottomed pan',
            'Add curry leaves, let them splutter',
            'Add onions, sauté until golden',
            'Add ginger-garlic paste and green chilies',
            'Add tomatoes, cook until soft',
            'Add all spices, cook 2 minutes',
            'Add coconut milk, bring to gentle boil',
            'Add tamarind paste, simmer 5 minutes',
            'Gently add fish pieces, cook 8-10 minutes',
            'Don\'t stir vigorously to avoid breaking fish',
            'Serve hot with steamed rice'
        ]
    },
    {
        id: 'mutton-rogan-josh',
        name: 'Mutton Rogan Josh',
        cuisine: 'indian',
        description: 'Kashmiri lamb curry in aromatic gravy with yogurt and traditional spices.',
        cookingTime: 90,
        serves: 4,
        ingredients: ['800g mutton/lamb, cut in pieces', '1 cup yogurt', '4 large onions, sliced', '2 tbsp ginger-garlic paste', '2 tsp red chili powder', '1 tsp turmeric', '2 tsp coriander powder', '1 tsp fennel powder', '4 green cardamom', '2 black cardamom', '4 cloves', '2 bay leaves', '1 cinnamon stick', '4 tbsp ghee', '1 tsp garam masala', 'Salt to taste', 'Fresh cilantro'],
        instructions: [
            'Marinate mutton with yogurt, turmeric, salt for 1 hour',
            'Deep fry sliced onions until golden, drain and crush',
            'Heat ghee, add whole spices',
            'Add ginger-garlic paste, cook 2 minutes',
            'Add marinated mutton, cook on high heat 10 minutes',
            'Add fried onion paste, all powdered spices',
            'Cook 5 minutes until oil separates',
            'Add hot water to cover meat',
            'Cover and cook 45 minutes until meat is tender',
            'Sprinkle garam masala and cilantro',
            'Serve hot with rice or naan'
        ]
    },
    {
        id: 'paratha',
        name: 'Aloo Paratha',
        cuisine: 'indian',
        description: 'Stuffed flatbread with spiced potato filling, popular North Indian breakfast.',
        cookingTime: 45,
        serves: 4,
        ingredients: ['For dough: 2 cups wheat flour', '1/2 tsp salt', 'Water as needed', 'For filling: 4 large potatoes, boiled and mashed', '2 green chilies, chopped', '1 inch ginger, chopped', '1 tsp cumin seeds', '1 tsp garam masala', '1/2 tsp red chili powder', '1/2 tsp amchur powder', '2 tbsp cilantro, chopped', 'Salt to taste', 'Ghee for cooking'],
        instructions: [
            'Mix flour and salt, add water gradually to make soft dough',
            'Rest dough for 30 minutes',
            'For filling: mix mashed potatoes with all spices and herbs',
            'Divide dough into small balls',
            'Roll each ball, place filling in center',
            'Gather edges and seal, flatten gently',
            'Roll again carefully to medium-thick circles',
            'Heat tawa or griddle',
            'Cook paratha until brown spots appear',
            'Flip, apply ghee, cook other side',
            'Serve hot with yogurt, pickle, and white butter'
        ]
    },
    {
        id: 'poha',
        name: 'Poha',
        cuisine: 'indian',
        description: 'Flattened rice cooked with onions, spices, and garnished with cilantro and lemon.',
        cookingTime: 20,
        serves: 4,
        ingredients: ['3 cups thick poha (flattened rice)', '2 large onions, chopped', '2 green chilies, chopped', '1/2 cup roasted peanuts', '2 tbsp oil', '1 tsp mustard seeds', '1 tsp cumin seeds', '10 curry leaves', '1/2 tsp turmeric', '1 tsp sugar', 'Salt to taste', '2 tbsp cilantro, chopped', '2 tbsp coconut, grated', 'Lemon juice'],
        instructions: [
            'Rinse poha gently in water, drain immediately',
            'Sprinkle salt and turmeric, mix lightly, set aside',
            'Heat oil in pan, add mustard and cumin seeds',
            'Add curry leaves, green chilies, let them splutter',
            'Add onions, sauté until translucent',
            'Add peanuts, cook 2 minutes',
            'Add seasoned poha, sugar, mix gently',
            'Cook 3-4 minutes on low heat',
            'Garnish with cilantro, coconut',
            'Serve hot with lemon juice'
        ]
    },
    {
        id: 'upma',
        name: 'Upma',
        cuisine: 'indian',
        description: 'South Indian breakfast dish made from semolina with vegetables and spices.',
        cookingTime: 25,
        serves: 4,
        ingredients: ['2 cups semolina (sooji/rava)', '3 cups water', '2 onions, chopped', '2 green chilies, chopped', '1 inch ginger, chopped', '1/4 cup mixed vegetables (carrot, beans, peas)', '2 tbsp oil', '1 tsp mustard seeds', '1 tsp cumin seeds', '1 tsp chana dal', '1 tsp urad dal', '10 curry leaves', '2 tbsp cilantro, chopped', 'Salt to taste', 'Lemon juice'],
        instructions: [
            'Dry roast semolina until light golden, set aside',
            'Heat oil, add mustard seeds, cumin seeds, both dals',
            'Add curry leaves, ginger, green chilies',
            'Add onions, sauté until soft',
            'Add mixed vegetables, cook 3 minutes',
            'Add water and salt, bring to boil',
            'Gradually add roasted semolina, stirring continuously',
            'Cook 5-7 minutes until water is absorbed',
            'Cover and let rest 5 minutes',
            'Garnish with cilantro and lemon juice',
            'Serve hot with coconut chutney'
        ]
    },
    {
        id: 'medu-vada',
        name: 'Medu Vada',
        cuisine: 'indian',
        description: 'Crispy South Indian lentil donuts, perfect with sambar and chutney.',
        cookingTime: 60,
        serves: 4,
        ingredients: ['2 cups urad dal (split black gram)', '2 green chilies, chopped', '1 inch ginger, chopped', '10 curry leaves, chopped', '1 tsp black pepper, crushed', '1/2 tsp asafoetida', 'Salt to taste', 'Oil for deep frying'],
        instructions: [
            'Soak urad dal for 4 hours, drain completely',
            'Grind to smooth, fluffy paste using minimal water',
            'Beat the batter for 5 minutes until very light',
            'Add green chilies, ginger, curry leaves, pepper, asafoetida, salt',
            'Mix well, batter should be thick but fluffy',
            'Heat oil for deep frying',
            'Wet hands, take portion of batter',
            'Shape into donuts with hole in center',
            'Gently slide into hot oil',
            'Fry until golden brown and crispy',
            'Drain on paper towels',
            'Serve hot with sambar and coconut chutney'
        ]
    },
    {
        id: 'rasam',
        name: 'Tomato Rasam',
        cuisine: 'indian',
        description: 'Tangy South Indian soup with tomatoes, tamarind, and aromatic spices.',
        cookingTime: 30,
        serves: 4,
        ingredients: ['4 large tomatoes, chopped', '1/4 cup toor dal, cooked', '2 tbsp tamarind paste', '2 tsp rasam powder', '1/2 tsp turmeric', '1 tsp salt', '2 tbsp ghee', '1 tsp mustard seeds', '1 tsp cumin seeds', '2 dried red chilies', '1/4 tsp asafoetida', '10 curry leaves', '2 tbsp cilantro, chopped', '3 cups water'],
        instructions: [
            'Cook tomatoes with little water until soft and mushy',
            'Add tamarind paste, rasam powder, turmeric, salt',
            'Add cooked dal and water, bring to boil',
            'Simmer 10 minutes until flavors blend',
            'Heat ghee in small pan for tempering',
            'Add mustard seeds, cumin seeds, red chilies',
            'Add asafoetida and curry leaves',
            'Pour tempering over rasam',
            'Simmer 2 more minutes',
            'Garnish with cilantro',
            'Serve hot with rice'
        ]
    },
    {
        id: 'coconut-chutney',
        name: 'Coconut Chutney',
        cuisine: 'indian',
        description: 'Classic South Indian chutney made with fresh coconut, perfect accompaniment for dosa and idli.',
        cookingTime: 15,
        serves: 4,
        ingredients: ['1 cup fresh coconut, grated', '2 green chilies', '1 inch ginger', '1/4 cup roasted chana dal', '10 curry leaves', '1/2 tsp salt', 'Water as needed', 'For tempering: 1 tbsp oil', '1 tsp mustard seeds', '1 tsp urad dal', '2 dried red chilies', '5 curry leaves'],
        instructions: [
            'Grind coconut, green chilies, ginger, chana dal with little water',
            'Add curry leaves and salt, grind to smooth paste',
            'Adjust consistency with water',
            'Transfer to serving bowl',
            'Heat oil for tempering',
            'Add mustard seeds, urad dal, red chilies',
            'Add curry leaves, let them splutter',
            'Pour tempering over chutney',
            'Mix gently and serve'
        ]
    },
    {
        id: 'gulab-jamun',
        name: 'Gulab Jamun',
        cuisine: 'indian',
        description: 'Sweet milk dumplings soaked in rose-flavored sugar syrup.',
        cookingTime: 60,
        serves: 6,
        ingredients: ['1 cup milk powder', '1/4 cup maida', '1/4 tsp baking soda', '2 tbsp ghee', '4-5 tbsp milk', 'Oil for frying', 'For syrup: 2 cups sugar', '2 cups water', '4 green cardamom', '1 tsp rose water', 'Few saffron strands'],
        instructions: [
            'Mix milk powder, maida, baking soda',
            'Add ghee, mix well',
            'Add milk gradually to form soft dough',
            'Rest dough 15 minutes',
            'Make sugar syrup by boiling sugar, water, cardamom',
            'Add rose water and saffron, keep warm',
            'Make small smooth balls from dough',
            'Heat oil on medium heat',
            'Fry jamuns until golden brown all over',
            'Immediately put hot jamuns in warm syrup',
            'Let them soak 2 hours before serving',
            'Serve warm or at room temperature'
        ]
    },
    {
        id: 'rasgulla',
        name: 'Rasgulla',
        cuisine: 'indian',
        description: 'Spongy cottage cheese balls cooked in sugar syrup, a Bengali delicacy.',
        cookingTime: 45,
        serves: 6,
        ingredients: ['1 liter full-fat milk', '2-3 tbsp lemon juice', '4 cups water', '1 cup sugar', '1/4 tsp cardamom powder'],
        instructions: [
            'Boil milk, add lemon juice to curdle',
            'Strain through muslin cloth, wash chenna under cold water',
            'Squeeze out excess water, knead chenna 5 minutes until smooth',
            'Make small smooth balls',
            'Boil water and sugar in wide pan',
            'Add chenna balls to boiling syrup',
            'Cover and cook 15-20 minutes on medium heat',
            'Rasgullas will double in size',
            'Add cardamom powder',
            'Cool completely before serving',
            'Serve chilled'
        ]
    },
    {
        id: 'kheer',
        name: 'Rice Kheer',
        cuisine: 'indian',
        description: 'Creamy rice pudding cooked in milk with cardamom and garnished with nuts.',
        cookingTime: 60,
        serves: 4,
        ingredients: ['1/4 cup basmati rice', '1 liter full-fat milk', '1/3 cup sugar', '4 green cardamom, crushed', '10 almonds, sliced', '10 cashews, chopped', '1 tbsp raisins', '1/4 tsp saffron strands', '1 tbsp ghee'],
        instructions: [
            'Wash and soak rice for 30 minutes',
            'Boil milk in heavy-bottomed pan',
            'Add drained rice, cook on low heat 30 minutes',
            'Stir frequently to prevent sticking',
            'When rice is completely soft and milk is thick, add sugar',
            'Add cardamom and saffron',
            'Heat ghee, fry almonds and cashews until golden',
            'Add fried nuts and raisins to kheer',
            'Cook 5 more minutes',
            'Serve hot or chilled',
            'Garnish with more nuts before serving'
        ]
    },
    {
        id: 'kulfi',
        name: 'Kulfi',
        cuisine: 'indian',
        description: 'Traditional Indian ice cream made with reduced milk and cardamom.',
        cookingTime: 300,
        serves: 6,
        ingredients: ['1 liter full-fat milk', '1/3 cup sugar', '4 green cardamom, powdered', '2 tbsp cornstarch', '1/4 cup almonds, chopped', '1/4 cup pistachios, chopped', '1 tbsp rose water (optional)'],
        instructions: [
            'Boil milk in heavy-bottomed pan',
            'Reduce heat, simmer until milk reduces to half',
            'Mix cornstarch with little cold milk',
            'Add cornstarch mixture to boiling milk',
            'Cook until thick, stirring continuously',
            'Add sugar, cardamom powder, rose water',
            'Add chopped nuts, mix well',
            'Cool completely',
            'Pour into kulfi molds or small cups',
            'Freeze 4-6 hours until set',
            'Dip molds in warm water to remove',
            'Serve immediately garnished with nuts'
        ]
    },
    {
        id: 'jalebi',
        name: 'Jalebi',
        cuisine: 'indian',
        description: 'Crispy, coiled sweet made from fermented batter and soaked in sugar syrup.',
        cookingTime: 90,
        serves: 4,
        ingredients: ['1 cup maida', '2 tbsp besan', '1/2 tsp baking powder', '1 tbsp yogurt', '1 tsp ghee', 'Water as needed', 'Oil for frying', 'For syrup: 2 cups sugar', '1 cup water', '1/4 tsp saffron', '1 tsp lemon juice', '1/2 tsp cardamom powder'],
        instructions: [
            'Mix maida, besan, baking powder',
            'Add yogurt, ghee, mix well',
            'Add water gradually to make smooth, thick batter',
            'Cover and ferment 8-12 hours',
            'Make sugar syrup by boiling sugar, water until sticky',
            'Add saffron, lemon juice, cardamom, keep warm',
            'Heat oil for frying',
            'Pour batter in plastic bottle with small hole',
            'Make spiral shapes directly in hot oil',
            'Fry until golden and crispy',
            'Immediately soak in warm syrup 2 minutes',
            'Serve hot or at room temperature'
        ]
    },
    {
        id: 'lassi',
        name: 'Mango Lassi',
        cuisine: 'indian',
        description: 'Refreshing yogurt-based drink blended with sweet mango pulp.',
        cookingTime: 10,
        serves: 2,
        ingredients: ['1 cup thick yogurt', '1/2 cup mango pulp', '3 tbsp sugar (adjust to taste)', '1/4 cup cold milk', '1/4 tsp cardamom powder', 'Ice cubes', 'Chopped pistachios for garnish'],
        instructions: [
            'Chill all ingredients beforehand',
            'Add yogurt, mango pulp, sugar in blender',
            'Add milk and cardamom powder',
            'Blend until smooth and frothy',
            'Add ice cubes, blend again',
            'Taste and adjust sweetness',
            'Pour in tall glasses',
            'Garnish with chopped pistachios',
            'Serve immediately'
        ]
    },
    {
        id: 'masala-chai',
        name: 'Masala Chai',
        cuisine: 'indian',
        description: 'Spiced tea with aromatic herbs and spices, India\'s favorite beverage.',
        cookingTime: 15,
        serves: 2,
        ingredients: ['2 cups water', '1/2 cup milk', '2 tsp black tea leaves', '2 tsp sugar', '2 green cardamom, crushed', '1 inch cinnamon stick', '3-4 cloves', '1/4 tsp fennel seeds', '1 inch ginger, crushed', '1/4 tsp black pepper powder'],
        instructions: [
            'Boil water with all whole spices and ginger',
            'Simmer 5 minutes until aromatic',
            'Add tea leaves, boil 2 minutes',
            'Add milk and sugar',
            'Bring to boil, reduce heat',
            'Simmer 3-4 minutes until color changes',
            'Add black pepper powder',
            'Strain and serve hot',
            'Adjust milk and sugar to taste'
        ]
    },
    {
        id: 'kachori',
        name: 'Dal Kachori',
        cuisine: 'indian',
        description: 'Deep-fried pastries stuffed with spiced lentil filling, popular North Indian snack.',
        cookingTime: 60,
        serves: 8,
        ingredients: ['For dough: 2 cups maida', '4 tbsp oil', '1/2 tsp salt', 'Water as needed', 'For filling: 1/2 cup moong dal', '1 tsp cumin seeds', '1 tsp fennel seeds', '2 green chilies, chopped', '1 inch ginger, chopped', '1 tsp red chili powder', '1/2 tsp garam masala', '1/2 tsp amchur powder', '2 tbsp oil', 'Salt to taste', 'Oil for frying'],
        instructions: [
            'Soak moong dal for 4 hours, drain and coarsely grind',
            'Heat oil, add cumin and fennel seeds',
            'Add ginger, green chilies, sauté briefly',
            'Add ground dal, all spices, salt',
            'Cook 8-10 minutes until dal is cooked, cool completely',
            'Make dough with maida, oil, salt, and water',
            'Rest dough 30 minutes',
            'Roll small circles, place filling in center',
            'Seal edges and shape into balls',
            'Deep fry on medium heat until golden and crispy',
            'Serve hot with mint chutney and tamarind chutney'
        ]
    },
    {
        id: 'dhokla',
        name: 'Khaman Dhokla',
        cuisine: 'indian',
        description: 'Spongy steamed Gujarati snack made from gram flour batter.',
        cookingTime: 45,
        serves: 4,
        ingredients: ['2 cups besan (gram flour)', '1 cup water', '1 tbsp ginger-green chili paste', '1 tsp salt', '1 tsp sugar', '2 tbsp oil', '1 tsp citric acid', '1 tsp baking soda', 'For tempering: 2 tbsp oil', '1 tsp mustard seeds', '1 tsp sesame seeds', '2 green chilies, slit', '10 curry leaves', '2 tbsp cilantro, chopped', '2 tbsp coconut, grated'],
        instructions: [
            'Mix besan with water to make smooth batter',
            'Add ginger-chili paste, salt, sugar, oil',
            'Beat well until light and fluffy',
            'Add citric acid and baking soda, mix gently',
            'Steam in greased pan for 15-20 minutes',
            'Check with toothpick, should come out clean',
            'Cool slightly, cut into squares',
            'Heat oil for tempering, add mustard seeds',
            'Add sesame seeds, green chilies, curry leaves',
            'Pour tempering over dhokla pieces',
            'Garnish with cilantro and coconut',
            'Serve with green chutney'
        ]
    },
    {
        id: 'pav-bhaji',
        name: 'Pav Bhaji',
        cuisine: 'indian',
        description: 'Mumbai street food consisting of spiced mixed vegetable curry served with buttered bread.',
        cookingTime: 45,
        serves: 4,
        ingredients: ['4 large potatoes, boiled', '1 cup cauliflower, chopped', '1 cup green peas', '1 cup mixed vegetables (carrot, beans)', '3 large onions, chopped', '4 tomatoes, chopped', '1 capsicum, chopped', '2 tbsp ginger-garlic paste', '3 tbsp pav bhaji masala', '1 tsp red chili powder', '4 tbsp butter', '2 tbsp oil', 'Salt to taste', '8 pav (bread rolls)', 'Chopped onions and cilantro for garnish', 'Lemon wedges'],
        instructions: [
            'Boil and mash all vegetables coarsely',
            'Heat butter and oil in heavy-bottomed pan',
            'Add onions, sauté until golden',
            'Add ginger-garlic paste, cook 2 minutes',
            'Add tomatoes, cook until soft',
            'Add capsicum, cook 3 minutes',
            'Add pav bhaji masala, chili powder',
            'Add mashed vegetables, mix well',
            'Cook 15 minutes, mashing continuously',
            'Add water if needed for consistency',
            'Slit and butter pav, toast on tawa',
            'Serve hot bhaji with pav, onions, cilantro, lemon'
        ]
    },
    {
        id: 'misal-pav',
        name: 'Misal Pav',
        cuisine: 'indian',
        description: 'Spicy Maharashtrian curry made with sprouted beans served with bread.',
        cookingTime: 60,
        serves: 4,
        ingredients: ['2 cups mixed sprouts (moong, matki)', '4 pav', '2 large onions, chopped', '3 tomatoes, chopped', '2 tbsp ginger-garlic paste', '2 tbsp misal masala', '1 tsp red chili powder', '1/2 tsp turmeric', '3 tbsp oil', 'Salt to taste', 'For garnish: Chopped onions', 'Cilantro', 'Farsan (mixture)', 'Lemon wedges'],
        instructions: [
            'Boil sprouts until soft but not mushy',
            'Heat oil, add onions, sauté until golden',
            'Add ginger-garlic paste, cook 2 minutes',
            'Add tomatoes, cook until soft',
            'Add misal masala, chili powder, turmeric',
            'Cook spices for 3-4 minutes',
            'Add cooked sprouts with cooking water',
            'Simmer 15 minutes until thick gravy forms',
            'Adjust consistency with water',
            'Season with salt',
            'Serve hot with pav',
            'Garnish with onions, cilantro, farsan, lemon'
        ]
    },
    {
        id: 'aloo-tikki',
        name: 'Aloo Tikki',
        cuisine: 'indian',
        description: 'Crispy potato patties served with chutneys, popular North Indian street food.',
        cookingTime: 40,
        serves: 4,
        ingredients: ['6 large potatoes, boiled', '2 tbsp cornstarch', '1 tsp cumin powder', '1 tsp garam masala', '1 tsp red chili powder', '1 tsp amchur powder', '2 green chilies, chopped', '2 tbsp cilantro, chopped', 'Salt to taste', 'Oil for shallow frying', 'Green chutney and tamarind chutney for serving'],
        instructions: [
            'Mash boiled potatoes when slightly warm',
            'Add cornstarch and all spices',
            'Add green chilies and cilantro',
            'Mix well and season with salt',
            'Make medium-sized round patties',
            'Heat oil in non-stick pan',
            'Cook tikkis on medium heat until golden',
            'Flip carefully and cook other side',
            'Cook until both sides are crispy',
            'Serve hot with green and tamarind chutneys',
            'Can be topped with yogurt and sev'
        ]
    },
    {
        id: 'paneer-butter-masala',
        name: 'Paneer Butter Masala',
        cuisine: 'indian',
        description: 'Rich and creamy paneer curry in tomato-cashew gravy with butter.',
        cookingTime: 45,
        serves: 4,
        ingredients: ['400g paneer, cubed', '4 large tomatoes', '10 cashews', '1 large onion, chopped', '2 tbsp ginger-garlic paste', '2 tsp red chili powder', '1 tsp garam masala', '1/2 tsp turmeric', '4 tbsp butter', '1/4 cup heavy cream', '1 tsp sugar', 'Salt to taste', 'Fresh cilantro'],
        instructions: [
            'Blanch tomatoes, peel and chop',
            'Soak cashews in hot water for 15 minutes',
            'Heat 2 tbsp butter, lightly fry paneer, set aside',
            'In same pan, sauté onions until golden',
            'Add ginger-garlic paste, cook 2 minutes',
            'Add tomatoes, cook until soft',
            'Add soaked cashews, cook 5 minutes',
            'Cool and blend to smooth paste',
            'Heat remaining butter, add paste',
            'Add spices, cook 5 minutes',
            'Add cream, sugar, salt',
            'Add fried paneer, simmer 10 minutes',
            'Garnish with cilantro, serve with naan'
        ]
    },
    {
        id: 'kadai-chicken',
        name: 'Kadai Chicken',
        cuisine: 'indian',
        description: 'Spicy chicken curry cooked with bell peppers and aromatic kadai masala.',
        cookingTime: 50,
        serves: 4,
        ingredients: ['800g chicken, cut in pieces', '2 large onions, sliced', '2 bell peppers, cut in strips', '4 tomatoes, chopped', '2 tbsp ginger-garlic paste', '2 tbsp kadai masala', '1 tsp red chili powder', '1/2 tsp turmeric', '3 tbsp oil', 'Salt to taste', 'Fresh cilantro', 'Ginger strips for garnish'],
        instructions: [
            'Heat oil in kadai or heavy-bottomed pan',
            'Add chicken pieces, cook until done, set aside',
            'In same oil, add onions, cook until golden',
            'Add ginger-garlic paste, cook 2 minutes',
            'Add tomatoes, cook until soft',
            'Add kadai masala, chili powder, turmeric',
            'Cook spices for 3-4 minutes',
            'Add bell peppers, cook 5 minutes',
            'Add cooked chicken, mix well',
            'Simmer 10 minutes until flavors blend',
            'Garnish with cilantro and ginger strips',
            'Serve hot with roti or rice'
        ]
    },
    {
        id: 'keema',
        name: 'Mutton Keema',
        cuisine: 'indian',
        description: 'Spiced minced mutton curry with peas, perfect with bread or rice.',
        cookingTime: 45,
        serves: 4,
        ingredients: ['500g mutton keema (minced)', '1 cup green peas', '2 large onions, chopped', '4 tomatoes, chopped', '2 tbsp ginger-garlic paste', '2 tsp red chili powder', '1 tsp turmeric', '2 tsp coriander powder', '1 tsp garam masala', '3 tbsp oil', 'Salt to taste', 'Fresh cilantro', 'Mint leaves'],
        instructions: [
            'Heat oil in heavy-bottomed pan',
            'Add onions, cook until golden brown',
            'Add ginger-garlic paste, cook 2 minutes',
            'Add keema, cook on high heat 10 minutes',
            'Break lumps and cook until water evaporates',
            'Add tomatoes and all spices',
            'Cook until tomatoes are soft',
            'Add green peas, mix well',
            'Cover and cook 15 minutes until keema is tender',
            'Add little water if needed',
            'Garnish with cilantro and mint',
            'Serve hot with roti or rice'
        ]
    },
    {
        id: 'chicken-65',
        name: 'Chicken 65',
        cuisine: 'indian',
        description: 'Crispy fried chicken pieces tossed in spicy South Indian sauce.',
        cookingTime: 40,
        serves: 4,
        ingredients: ['500g chicken, cut in small pieces', '2 tbsp ginger-garlic paste', '1 tbsp red chili powder', '1/2 tsp turmeric', '1 tbsp lemon juice', '2 tbsp yogurt', 'Salt to taste', 'For batter: 4 tbsp maida', '2 tbsp cornstarch', 'Water as needed', 'Oil for frying', 'For tossing: 2 tbsp oil', '10 curry leaves', '3 green chilies, slit', '1 tsp ginger-garlic paste', '1 tbsp soy sauce'],
        instructions: [
            'Marinate chicken with ginger-garlic paste, chili powder, turmeric, lemon juice, yogurt, salt for 30 minutes',
            'Make batter with maida, cornstarch, and water',
            'Dip marinated chicken in batter',
            'Deep fry until golden and crispy',
            'Drain on paper towels',
            'Heat oil in pan, add curry leaves',
            'Add green chilies and ginger-garlic paste',
            'Add soy sauce, toss fried chicken',
            'Cook 2 minutes until well coated',
            'Serve hot as appetizer',
            'Garnish with onion slices and lemon wedges'
        ]
    },
    {
        id: 'mysore-pak',
        name: 'Mysore Pak',
        cuisine: 'indian',
        description: 'Rich South Indian sweet made with gram flour, sugar, and ghee.',
        cookingTime: 30,
        serves: 8,
        ingredients: ['1 cup besan (gram flour)', '1 cup sugar', '3/4 cup ghee', '1/4 cup water', 'Pinch of cardamom powder'],
        instructions: [
            'Roast besan on low heat until aromatic',
            'Make sugar syrup with sugar and water',
            'Cook until one-string consistency',
            'Heat ghee in another pan',
            'Add roasted besan to hot ghee',
            'Mix continuously to avoid lumps',
            'Gradually add hot sugar syrup',
            'Cook stirring continuously until mixture thickens',
            'Add cardamom powder',
            'Pour into greased plate',
            'Cool and cut into squares',
            'Store in airtight container'
        ]
    },
    {
        id: 'halwa',
        name: 'Gajar Halwa',
        cuisine: 'indian',
        description: 'Traditional carrot pudding cooked in milk with nuts and cardamom.',
        cookingTime: 60,
        serves: 6,
        ingredients: ['1 kg fresh carrots, grated', '1 liter full-fat milk', '1/2 cup sugar', '4 tbsp ghee', '4 green cardamom, powdered', '10 almonds, sliced', '10 cashews, chopped', '1 tbsp raisins'],
        instructions: [
            'Heat ghee in heavy-bottomed pan',
            'Add grated carrots, cook 10 minutes',
            'Add milk, bring to boil',
            'Cook on medium heat until milk reduces',
            'Stir frequently to prevent sticking',
            'When milk is almost absorbed, add sugar',
            'Cook until sugar dissolves and halwa thickens',
            'Add cardamom powder',
            'Fry nuts in little ghee, add to halwa',
            'Cook 5 more minutes',
            'Serve hot or cold',
            'Garnish with more nuts'
        ]
    },
    {
        id: 'seekh-kebab',
        name: 'Seekh Kebab',
        cuisine: 'indian',
        description: 'Spiced minced meat kebabs grilled on skewers, popular Mughlai dish.',
        cookingTime: 45,
        serves: 4,
        ingredients: ['500g mutton keema', '2 tbsp ginger-garlic paste', '2 green chilies, chopped', '1 large onion, finely chopped', '2 tsp red chili powder', '1 tsp garam masala', '1 tsp cumin powder', '2 tbsp cilantro, chopped', '2 tbsp mint, chopped', '1 egg', 'Salt to taste', '2 tbsp oil'],
        instructions: [
            'Mix keema with all ingredients except oil',
            'Add egg and mix well',
            'Refrigerate mixture for 2 hours',
            'Wet hands and shape mixture around skewers',
            'Preheat grill or oven to 200°C',
            'Brush kebabs with oil',
            'Grill 15-20 minutes, turning occasionally',
            'Cook until browned and cooked through',
            'Baste with oil while cooking',
            'Serve hot with mint chutney',
            'Garnish with onion rings and lemon'
        ]
    },
    {
        id: 'uttapam',
        name: 'Uttapam',
        cuisine: 'indian',
        description: 'Thick South Indian pancake topped with vegetables, made from dosa batter.',
        cookingTime: 30,
        serves: 4,
        ingredients: ['2 cups dosa batter', '1 large onion, chopped', '2 tomatoes, chopped', '2 green chilies, chopped', '1/4 cup cilantro, chopped', '1 carrot, finely chopped', '1/4 cup coconut, grated', 'Oil for cooking', 'Salt to taste'],
        instructions: [
            'Mix chopped vegetables with little salt',
            'Heat non-stick pan or tawa',
            'Pour thick layer of batter, spread gently',
            'Sprinkle vegetable mixture on top',
            'Press gently with spatula',
            'Drizzle oil around edges',
            'Cook on medium heat until bottom is golden',
            'Flip carefully and cook other side',
            'Cook until both sides are done',
            'Serve hot with sambar and chutney',
            'Can make individual small uttapams'
        ]
    },
    {
        id: 'rava-kesari',
        name: 'Rava Kesari',
        cuisine: 'indian',
        description: 'South Indian semolina sweet flavored with saffron and cardamom.',
        cookingTime: 25,
        serves: 4,
        ingredients: ['1 cup semolina (rava)', '1 cup sugar', '2.5 cups water', '4 tbsp ghee', '10 cashews', '1 tbsp raisins', 'Pinch of saffron', '1/4 tsp cardamom powder', 'Few drops orange food color (optional)'],
        instructions: [
            'Roast semolina in dry pan until aromatic',
            'Heat ghee, fry cashews and raisins',
            'Remove and keep aside',
            'Add roasted semolina to remaining ghee',
            'Boil water with saffron and food color',
            'Gradually add hot water to semolina',
            'Stir continuously to avoid lumps',
            'Cook until water is absorbed',
            'Add sugar, mix well',
            'Cook until sugar dissolves',
            'Add cardamom powder',
            'Garnish with fried nuts and raisins',
            'Serve hot'
        ]
    },
    {
        id: 'appam',
        name: 'Appam',
        cuisine: 'indian',
        description: 'South Indian fermented rice pancakes with soft center and crispy edges.',
        cookingTime: 240,
        serves: 6,
        ingredients: ['2 cups raw rice', '1/2 cup cooked rice', '1/2 cup coconut, grated', '1/2 tsp active dry yeast', '1/4 tsp sugar', '1/2 cup coconut milk', 'Salt to taste', 'Oil for cooking'],
        instructions: [
            'Soak raw rice for 4 hours',
            'Grind soaked rice, cooked rice, coconut with little water',
            'Dissolve yeast with sugar in warm water',
            'Add yeast mixture to rice paste',
            'Add coconut milk and salt',
            'Mix well, ferment overnight',
            'Heat appam pan or wok',
            'Pour batter, swirl to coat sides',
            'Cover and cook until edges are crispy',
            'Center should be soft and spongy',
            'Serve hot with coconut milk curry',
            'Can be sweet or savory'
        ]
    },
    {
        id: 'puttu',
        name: 'Puttu',
        cuisine: 'indian',
        description: 'Kerala breakfast dish of steamed rice flour cylinders with coconut.',
        cookingTime: 30,
        serves: 4,
        ingredients: ['2 cups puttu flour (rice flour)', '3/4 cup water', '1/2 tsp salt', '1 cup coconut, grated', '2 tbsp jaggery (optional)'],
        instructions: [
            'Mix rice flour with salt',
            'Sprinkle water gradually while mixing',
            'Rub mixture until it holds together when pressed',
            'Layer coconut and rice flour mixture in puttu maker',
            'Start with coconut, alternate layers',
            'Top with coconut',
            'Steam for 10-15 minutes',
            'Remove from molds carefully',
            'Serve hot with banana and jaggery',
            'Can serve with kadala curry',
            'Best eaten fresh and hot'
        ]
    },
    {
        id: 'fish-fry',
        name: 'Kerala Fish Fry',
        cuisine: 'indian',
        description: 'Spicy South Indian fish fry marinated with aromatic spices.',
        cookingTime: 30,
        serves: 4,
        ingredients: ['500g fish fillets (kingfish or pomfret)', '2 tbsp red chili powder', '1 tbsp coriander powder', '1/2 tsp turmeric', '1 tbsp ginger-garlic paste', '1 tbsp lemon juice', '2 tbsp rice flour', '1 tsp garam masala', 'Salt to taste', 'Oil for frying', 'Curry leaves for garnish'],
        instructions: [
            'Cut fish into medium pieces',
            'Mix all spices with lemon juice',
            'Marinate fish with spice paste for 30 minutes',
            'Add rice flour, mix gently',
            'Heat oil in heavy-bottomed pan',
            'Fry fish pieces until golden brown',
            'Don\'t overcrowd the pan',
            'Fry until crispy on both sides',
            'Drain on paper towels',
            'Garnish with fried curry leaves',
            'Serve hot with rice and rasam',
            'Squeeze lemon before eating'
        ]
    },
    {
        id: 'prawn-curry',
        name: 'Goan Prawn Curry',
        cuisine: 'indian',
        description: 'Coastal curry with prawns in coconut milk and Goan spices.',
        cookingTime: 35,
        serves: 4,
        ingredients: ['500g large prawns, cleaned', '400ml coconut milk', '2 large onions, sliced', '4 tomatoes, chopped', '2 tbsp ginger-garlic paste', '2 tsp red chili powder', '1 tsp turmeric', '1 tsp coriander powder', '1 tbsp tamarind paste', '2 tbsp coconut oil', '10 curry leaves', '2 green chilies, slit', 'Salt to taste'],
        instructions: [
            'Clean prawns, marinate with turmeric and salt',
            'Heat coconut oil, add curry leaves',
            'Add onions, sauté until golden',
            'Add ginger-garlic paste and green chilies',
            'Add tomatoes, cook until soft',
            'Add chili powder, coriander powder, cook 2 minutes',
            'Add coconut milk, bring to gentle boil',
            'Add tamarind paste, simmer 5 minutes',
            'Add prawns, cook 5-7 minutes',
            'Don\'t overcook prawns',
            'Adjust seasoning with salt',
            'Serve hot with steamed rice'
        ]
    },
    {
        id: 'papdi-chaat',
        name: 'Papdi Chaat',
        cuisine: 'indian',
        description: 'Popular North Indian street food with crispy wafers, yogurt, and chutneys.',
        cookingTime: 20,
        serves: 4,
        ingredients: ['20 papdi (crispy wafers)', '1 cup boiled potatoes, cubed', '1 cup boiled chickpeas', '1 cup thick yogurt', '1/2 cup green chutney', '1/2 cup tamarind chutney', '1 large onion, chopped', '2 tomatoes, chopped', '1 tsp chaat masala', '1/2 tsp roasted cumin powder', '1/4 cup sev', '2 tbsp cilantro, chopped'],
        instructions: [
            'Arrange papdis on serving plate',
            'Top each papdi with potatoes and chickpeas',
            'Add chopped onions and tomatoes',
            'Whisk yogurt until smooth',
            'Pour yogurt over papdis',
            'Drizzle green and tamarind chutneys',
            'Sprinkle chaat masala and cumin powder',
            'Top with sev and cilantro',
            'Serve immediately before papdis get soggy',
            'Can assemble individual servings',
            'Adjust chutneys according to taste'
        ]
    },
    {
        id: 'rajasthani-dal-baati',
        name: 'Dal Baati Churma',
        cuisine: 'indian',
        description: 'Traditional Rajasthani dish with baked wheat balls, lentil curry, and sweet crumbs.',
        cookingTime: 90,
        serves: 6,
        ingredients: ['For Baati: 2 cups wheat flour', '1/4 cup semolina', '1/4 cup ghee', '1/2 tsp salt', 'Water as needed', 'For Dal: 1/2 cup each - toor, moong, chana dal', '2 tbsp ghee', '1 tsp cumin seeds', '2 green chilies', '1 inch ginger', '1/2 tsp turmeric', '1 tsp red chili powder', 'Salt to taste', 'For Churma: 1 cup coarse wheat flour', '1/2 cup ghee', '1/2 cup jaggery powder'],
        instructions: [
            'Mix flour, semolina, ghee, salt, make stiff dough',
            'Make balls, bake at 180°C for 45 minutes',
            'Cook mixed dals until soft',
            'Heat ghee, add cumin, ginger, chilies',
            'Add cooked dal, spices, simmer 15 minutes',
            'For churma: roast coarse flour in ghee',
            'Add jaggery, mix well',
            'Break hot baatis, soak in ghee',
            'Serve with dal and churma',
            'Traditional combination meal',
            'Very popular in Rajasthan'
        ]
    },
    {
        id: 'bengali-fish-curry',
        name: 'Bengali Fish Curry',
        cuisine: 'indian',
        description: 'Traditional Bengali fish curry with mustard oil and panch phoron spices.',
        cookingTime: 35,
        serves: 4,
        ingredients: ['500g rohu or katla fish, cut in pieces', '2 large potatoes, quartered', '3 tbsp mustard oil', '1 tsp panch phoron', '2 bay leaves', '2 green chilies, slit', '1 tsp ginger paste', '1/2 tsp turmeric', '1 tsp red chili powder', '1 tsp cumin powder', '2 tomatoes, chopped', '1 tsp sugar', 'Salt to taste', 'Cilantro for garnish'],
        instructions: [
            'Marinate fish with turmeric and salt',
            'Heat mustard oil until smoking, cool slightly',
            'Fry fish pieces until golden, set aside',
            'Fry potato pieces, set aside',
            'Add panch phoron and bay leaves to oil',
            'Add ginger paste and green chilies',
            'Add tomatoes, cook until soft',
            'Add turmeric, chili powder, cumin powder',
            'Add little water, bring to boil',
            'Add fried potatoes, cook 5 minutes',
            'Gently add fish, add sugar',
            'Simmer 8-10 minutes, garnish with cilantro',
            'Serve with steamed rice'
        ]
    },
    {
        id: 'hyderabadi-haleem',
        name: 'Hyderabadi Haleem',
        cuisine: 'indian',
        description: 'Rich Hyderabadi stew made with lentils, wheat, and meat, slow-cooked to perfection.',
        cookingTime: 180,
        serves: 6,
        ingredients: ['500g mutton, cut in pieces', '1/2 cup each: wheat, barley, chana dal', '1/4 cup each: moong dal, masoor dal', '4 large onions, sliced and fried', '2 tbsp ginger-garlic paste', '2 tsp red chili powder', '1 tsp turmeric', '2 tsp garam masala', '1/4 cup ghee', 'Salt to taste', 'For garnish: Fried onions, mint, cilantro, lemon, fried almonds'],
        instructions: [
            'Soak wheat and barley overnight',
            'Pressure cook mutton until very tender',
            'Cook soaked grains and dals until very soft',
            'Mash everything together until smooth paste forms',
            'Heat ghee, add ginger-garlic paste',
            'Add cooked meat with stock',
            'Add mashed grain-dal mixture',
            'Cook on low heat 1 hour, stirring frequently',
            'Add fried onions, spices',
            'Cook until thick, creamy consistency',
            'Garnish with fried onions, herbs, nuts',
            'Serve hot with naan or rice'
        ]
    },
    {
        id: 'kashmiri-rogan-josh',
        name: 'Kashmiri Rogan Josh',
        cuisine: 'indian',
        description: 'Authentic Kashmiri lamb curry with aromatic spices and yogurt.',
        cookingTime: 120,
        serves: 6,
        ingredients: ['1 kg lamb, cut in pieces', '1 cup yogurt', '4 large onions, sliced', '2 tbsp Kashmiri red chili powder', '1 tsp turmeric', '2 tsp fennel powder', '1 tsp ginger powder', '1 tsp dry mint powder', '6 green cardamom', '4 cloves', '2 black cardamom', '2 bay leaves', '1 cinnamon stick', '4 tbsp ghee', 'Salt to taste'],
        instructions: [
            'Marinate lamb with yogurt and salt for 2 hours',
            'Deep fry onions until golden, drain and crush',
            'Heat ghee, add whole spices',
            'Add marinated lamb, cook on high heat 15 minutes',
            'Add fried onion paste, mix well',
            'Add Kashmiri chili powder, turmeric',
            'Add fennel powder, ginger powder',
            'Cook until oil separates',
            'Add hot water to cover meat',
            'Cover and cook 1 hour until tender',
            'Add dry mint powder in last 10 minutes',
            'Serve hot with steamed rice'
        ]
    },
    {
        id: 'gujarati-dhokla',
        name: 'Gujarati Dhokla',
        cuisine: 'indian',
        description: 'Spongy steamed savory cake from Gujarat made with fermented gram flour batter.',
        cookingTime: 60,
        serves: 6,
        ingredients: ['2 cups gram flour (besan)', '1 cup water', '1 tbsp ginger-green chili paste', '1 tsp salt', '1 tsp sugar', '2 tbsp oil', '1 tbsp lemon juice', '1 tsp eno fruit salt', 'For tempering: 2 tbsp oil', '1 tsp mustard seeds', '1 tsp sesame seeds', '4-5 green chilies, slit', '1 inch ginger, julienned', '8-10 curry leaves', '2 tbsp cilantro, chopped', '2 tbsp coconut, grated'],
        instructions: [
            'Make smooth batter with besan and water',
            'Add ginger-chili paste, salt, sugar, oil',
            'Beat until light and fluffy',
            'Add lemon juice, mix well',
            'Add eno, mix gently, pour in greased pan',
            'Steam for 20-25 minutes until cooked',
            'Cool and cut into squares',
            'Heat oil for tempering',
            'Add mustard seeds, sesame seeds',
            'Add chilies, ginger, curry leaves',
            'Pour over dhokla pieces',
            'Garnish with cilantro and coconut',
            'Serve with green chutney'
        ]
    }
];

module.exports = recipes;